cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views
from django.urls import path, re_path






urlpatterns = [
   

      # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')),
    re_path(r'', include('account.urls')),
    re_path(r'cart', include('cart.urls')),
    re_path(r'orders/', include('orders.urls')),
    re_path(r'', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from . import views

app_name = 'shop'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^vendorrequest/', views.vendorrequest, name='vendorrequest'),
    url(r'^Vendorfaqs/', views.Vendorfaqs, name='Vendorfaqs'),
    url(r'^log/', views.log, name='log'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^mens/', views.mens, name='mens'),
    url(r'^womens/', views.womens, name='womens'),
    url(r'^decorbeauty/', views.decorbeauty, name='decorbeauty'),
    url(r'^homeaccesories/', views.homeaccesories, name='homeaccesories'),
    url(r'^negotiate/price/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.client_price, name='client_price'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^negotiate/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.negotiate, name='negotiate'),

   
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),

    url(r'^(?P<subcategory_slug>[-\w]+)/$',
        views.subcategory_list, name='product_list_by_subcategory'),
    url(r'^(?P<minicategory_slug>[-\w]+)/$',
        views.minicategory_list, name='product_list_by_minicategory')




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, NumberInput, EmailInput
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



class NegotiateForm(forms.Form):
    client_price = forms.CharField(
        label='Your price',
        max_length=100,
        widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Your price'}),
        required=True,
    )

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, SubCategory, MiniCategory
from .forms import NegotiateForm
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import Client
from django.db.models import Count

@login_required(login_url ='login:login_redirect')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    client = Client.objects.get(user=request.user)
    client_orders = client.no_of_orders
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    return render(request, 'shop/product/list.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'client_orders':client_orders,
        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def subcategory_list(request, subcategory_slug=None):
    subcategory = None
    subcategories = Category.SubCategory.objects.all()
    products = Product.subcategory.objects.filter(available=True)
    if category_slug:
        subcategory = get_object_or_404(SubCategory, slug=SubCategory_slug)
        products = Product.objects.filter(subcategory=subcategory)

    context = {

        'subcategory': subcategory,
        'subcategories': subcategories,
        'products': products,

    }
    return render(request, 'shop/product/sublist.html', context)


def minicategory_list(request, minicategory_slug=None):
    minicategory = None
    minicategories = Category.SubCategory.MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        minicategory = get_object_or_404(MiniCategory, slug=MiniCategory_slug)
        products = Product.objects.filter(minicategory=minicategory)

    context = {

        'minicategory': minicategory,
        'minicategories': minicategories,
        'products': products,

    }

    return render(request, 'shop/product/minilist.html', context)

# @login_required(login_url='/accounts/login/')
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     cart_product_form = CartAddProductForm()
#     context = {
#         'product': product,
#         'cart_product_form': cart_product_form
#     }
#     return render(request, 'shop/product/detail.html', context)

@login_required(login_url ='login:login_redirect')
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    client = Client.objects.get(user=request.user)
    cart_product_form = CartAddProductForm()
    product_tags_ids = Product.tags.values_list('id', flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags_ids)\
    .exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('tags'))\
    .order_by('-same_tags','-created_at')[:6]
    context = {
        'product': product,
        'client':client,
        'product_tags_ids':product_tags_ids,
        'similar_products':similar_products,
        'cart_product_form': cart_product_form
    }
  
    return render(request, 'shop/product/detail.html',
                  context={
                      'product': product,
                      'cart_product_form': cart_product_form,
                      'product_tags_ids':product_tags_ids,
                      'similar_products':similar_products,
                      'local_css_urls': ["css3/easy-responsive-tabs.css",
                                         "css3/material-kit.min1036.css",
                                         "css3/demo.css",
                                         "css3/vertical-nav.css"],
                      'local_js_urls': ["core/jquery.min.js",
                                        "core/popper.min.js",
                                        "core/bootstrap-material-design.min.js",
                                        "js3/vertical-nav.js",
                                        "js3/material-kit.min1036.js",
                                        "js3/demo.js",
                                        "js3/buttons.js",
                                        "js3/modernizr.js",
                                        "js3/bootstrap.min.js",
                                        "js3/plugins/moment.min.js ",
                                        "js3/plugins/bootstrap-datetimepicker.js",
                                        "js3/plugins/jquery.flexisel.js",
                                        "js3/plugins/jquery.sharrre.js",
                                        "js3/plugins/nouislider.min.js",
                                        "js3/plugins/bootstrap-selectpicker.js",
                                        "js3/plugins/bootstrap-tagsinput.js",
                                        "js3/plugins/jasny-bootstrap.min.js"],
                  })


# homepage view

def home(request, category_slug=None, subcategory_slug=None, minicategory_slug=None):
    category = None
    subcategory = None
    minicategory = None
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    minicategories = MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        subcategories = SubCategory.objects.filter(category=category)

    # if subcategory_slug:
    #     subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
    #     minicategories = MiniCategory.objects.filter(available=True)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories ': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,
    }

    return render(request, 'shop/homepage/page/home.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,

        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def log(request):
    return render(request, 'shop/product/login2.html', {
        'tab': 'registration',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",

shop/views/forgot_password.py
import json
import random, string
from django.shortcuts import render
from django.core import serializers
from landpage.form import ForgotPasswordForm
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail

def forgot_password_page(request):
    form = ForgotPasswordForm()
    return render(request, 'offlandpage/page/forgot_password.html',{
        'form': form,
        'tab': 'forget_password',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })


def reset_password(request):
    response_data = {'status' : 'failure', 'message' : 'unknown error occured' }
    if request.is_ajax():
        if request.method == 'POST':
            form = ForgotPasswordForm(request.POST)
            # Validate the form: the captcha field will automatically
            # check the input
            if form.is_valid():
                # Get the email and then create a random password for the client
                # and send the client the new password to their email address.
                email = request.POST['email']
                new_password = create_random_password(email)
                response_data = send_email(email, new_password)
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


def random_word(length):
    return ''.join(random.choice("abcdefghijklmnopqrstuvwxyz123467890") for i in range(length))


def create_random_password(email):
    # Create new password
    new_password = random_word(8)
    
    # Update the user account
    user = User.objects.get(email=email)
    user.set_password(new_password)
    user.save()
    
    # Return the new password
    return new_password


def send_email(email, new_password):
    if settings.EMAIL_HOST_USER is '' or settings.EMAIL_HOST_PASSWORD is '':
        return {'status' : 'failed', 'message' : 'cannot change password, emailer is offline, please check back later' }
    
    text = "Your new password is: " + new_password
            
    send_mail(
        "New Password",
        text,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False
    )
    return {'status' : 'success', 'message' : 'successfully registered' }

shop/views/google.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.conf import settings


def google_verify_page(request):
    return render(request, 'misc/google.html',{})

shop/views/landpageprod.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings

shop/views/privacy.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def privacy_page(request):
    return render(request, 'offlandpage/page/privacy.html',{
        'tab': 'privacy',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/terms.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def terms_page(request):
    return render(request, 'offlandpage/page/terms.html',{
        'tab': 'terms',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/txt.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def robots_txt_page(request):
    return render(request, 'misc/robots.txt', {}, content_type="text/plain")


def humans_txt_page(request):
    return render(request, 'misc/humans.txt', {}, content_type="text/plain")


def terms_txt_page(request):
    return render(request, 'misc/terms.txt', {}, content_type="text/plain")


def privacy_txt_page(request):
    return render(request, 'misc/privacy.txt', {}, content_type="text/plain")

shop/templates/shop/product/about.html
{% extends 'shop/base2.html' %}
{% load static %}



{% block content %}
<body class="about-us sidebar-collapse">



	<div class="" style="margin-top: 50px">
	  <div class="container">
	
		<div class="about-team team-1">
		  <div class="row">
			<div class="col-md-8 ml-auto mr-auto text-center">
				<h2 class="title">About Us</h2>
				<h4>Meet the amazing team behind this project and find out more about how we work.</h4>
			</div>
			</div>
			<div class="about-description text-center">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h5 class="description"><strong>Jadili mall </strong> is an African Online store, that provides an opportunity for our local artisans, fashion project owners and designers to showcase and sell their unique african designs ranging from furniture (home decor, office decor), Aparel, jewellery and so on. Offering customers Africa's diverse Fashion taste under one roof.</h5>
          </div>
        </div>
			</div>
			
		
			

	  </div>
	</div>
	<footer class="footer">
	  <div class="container">
	
		<div class="copyright pull-center">
			Copyright &#xA9;
			<script>
				document.write(new Date().getFullYear())
			</script> Jadili mall  
			</div>
	  </div>
	</footer>
  
  
  
  


  

  </body>
  
{% endblock %}

shop/templates/shop/product/contact.html
{% extends 'shop/base2.html' %}
{% load static %}



{% block content %}
<!-- Start of Async Drift Code -->

	<!-- End of Async Drift Code -->

	<body class="contact-page sidebar-collapse" >
	
		<div id="contactUsMap" class="big-map" ></div>
		<div class="" style="margin-top: 200px;">
		  <div class="contact-content">
			<div class="container">
			  <h2 class="title">Send us a message</h2>
			  <div class="row">
				<div class="col-md-6">
				  <p class="description">You can contact us with anything related to our Products. We&apos;ll get in touch with you as soon as possible.
					<br>
					<br>
				  </p>
				  <form role="form" id="contact-form" method="post">
					<div class="form-group">
					  <label for="name" class="bmd-label-floating">Your name</label>
					  <input type="text" class="form-control" id="name">
					</div>
					<div class="form-group">
					  <label for="exampleInputEmails" class="bmd-label-floating">Email address</label>
					  <input type="email" class="form-control" id="exampleInputEmails">
					  <span class="bmd-help">We'll never share your email with anyone else.</span>
					</div>
					<div class="form-group">
					  <label for="phone" class="bmd-label-floating">Phone</label>
					  <input type="text" class="form-control" id="phone">
					</div>
					<div class="form-group label-floating">
					  <label class="form-control-label bmd-label-floating" for="message"> Your message</label>
					  <textarea class="form-control" rows="6" id="message"></textarea>
					</div>
					<div class="submit text-center">
					  <input type="submit" class="btn btn-primary btn-raised btn-round" value="Contact Us">
					</div>
				  </form>
				</div>
			
			  </div>
			</div>
		  </div>
		</div>
		<footer class="footer">
			<div class="container">
	
			  <div class="copyright pull-center">
				  Copyright &#xA9;
				  <script>
					  document.write(new Date().getFullYear())
					</script> jadili mall 
				  </div>
			</div>
		  </footer>


  {% endblock %}

shop/templates/shop/product/decorbeauty.html
{% extends 'shop/base.html' %}
{% load static %}



{% block content %}
<div class="col-md-4 modal_body_right modal_body_right1">

					</div>
				</div>
			</div>
			<!-- //Modal content-->
		</div>
	</div>
<!-- //Modal2 -->
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
	<div class="container">
		<h3>Decor &<span> Beauty  </span></h3>
		<h3><span>COMING </span> SOON  </h3>
		<!--/w3_short-->
			 <div class="services-breadcrumb">
					<div class="agile_inner_breadcrumb">

						 <ul class="w3_short">
							<li><a href="{% url 'shop:home' %}">Home</a><i>|</i></li>
							<li>Decor beauty</li>
						
						</ul>
					 </div>
			</div>
	 <!--//w3_short-->
</div>
</div>
{% endblock %}

shop/templates/shop/product/homeaccesories.html
{% extends 'shop/base.html' %}
{% load static %}



{% block content %}
<div class="col-md-4 modal_body_right modal_body_right1">

					</div>
				</div>
			</div>
			<!-- //Modal content-->
		</div>
	</div>
<!-- //Modal2 -->
<!-- /banner_bottom_agile_info -->
<div class="page-head_agile_info_w3l">
	<div class="container">
		<h3>Home<span> ACCESORIES </span></h3>
		<h3><span>COMING</span>SOON</h3>
		<!--/w3_short-->
			 <div class="services-breadcrumb">
					<div class="agile_inner_breadcrumb">

						 <ul class="w3_short">
							<li><a href="{% url 'shop:home' %}">Home</a><i>|</i></li>
							<li>HOME Accesories</li>
						</ul>
					 </div>
			</div>
	 <!--//w3_short-->
</div>
</div>
  {% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}
{% block content %}
 

<br><br><br><br><br><br>

<div class="container">

    <div class="col-md-4 ml-auto mr-auto text-center">
                
        <button type="button" class="btn btn-white">  Categories</button>
    
      </div>
        <div class="row mr-auto pt-8 pt-lg-0">
           
           
                <div class="">
                        {% for c in categories %}

                        <a class="btn btn-sm btn-white" style="color:rgb(0, 255, 255); background-color:#ffffff " href="{{ c.get_absolute_url }}" >{{ c.name }}</a>

                            
                        {% endfor %}    
                               
                              
            
                      
                 
                      </div>
                <!-- <div class="col-md-12 ml-auto ">
                       <ul class="nav flexi-nav text-center" data-tabs="tabs" id="flexiselDemo1">
                    
                               <li class="nav-item">
                                    {% for c in categories %}
                                       <button class="btn btn-sm btn-white  "> <a  href="{{ product.category.get_absolute_url }}">{{ c.name}} <i class="material-icons">keyboard_arrow_right</i> </a></button>
                                       {% endfor %}
                               </li>
                              
                             </ul>
                  </div> -->

        </div>
    <div class="row">
        <!-- <div class="col-12 col-sm-3">
            <div class="card card-nav-tabs card-plain ">
                <div class="card-header card-header-success"> 
                  <div class="nav-tabs-navigation  ">
                    <div class="nav-tabs-wrapper">
                      <ul class="nav nav-tabs" data-tabs="tabs">
                    <h4 class=" text-center">Categories</h4>
                     
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="" >
                  <div class="tab-content text-center">
                    <div class="tab-pane active" >
                        <li class="nav-link " {% if not category %} class="active"{% endif %}>
                          <a href="{% url 'shop:product_list' %}">All</a>
                        </li>
                        <li class="nav-link "{% if category.slug == c.slug %} class="active"{% endif %}>
                            {% for c in categories %}
                          <a class="nav-link " href="{{ c.get_absolute_url }}"  >{{ c.name }}</a>
                        </li>
                        {% endfor %}
                    </div>
                
                  </div>
                </div>
              </div>
        
        </div> -->
        <div class="col">
            <div class="row">
                    {% if products%}
                {% for product in products %}  
                <div class="col-12 col-md-6 col-lg-3">
             
                    <div class="card  ">
                        <div class="card-header card-header-image">
                          <a href="{{ product.get_absolute_url }}">
                            <img class="img" href="{{ product.get_absolute_url }}" src="{% if product.image %} {{ product.image.cdn_url }} {% else %} {% static 'img/default.png' %} {% endif %}" >
                          </a>
                        </div>
                        <div class="card-body text-center  " style="color:rgb(235, 235, 235)">
                          <h6 class="card-category text-success">
                            <i class="material-icons">trending_up</i> Trending
                          </h6>
                          <h4 class="card-title">
                              <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                          </h4>
                          <div class="description  ">
                              <h4 class="info-title ">KSH {{ product.price }}</h4> 
                          </div>
                          <a href="{{ product.get_absolute_url }}" >
                              <i class="material-icons">explore</i> Quick view
                            </a>
                            <div>
                                <a  href="{% url 'shop:client_price' id=product.id  slug=product.slug %}"><input style="background-color:#FD8C04" type="submit" name="submit" value="Negotiate price" class="btn  btn-primary  btn-round btn-sm" />

                                    <a  href="{{ product.get_absolute_url }}"><input  type="submit" name="submit" value="Add to cart" class="btn  btn-primary  btn-round btn-sm" /> 
                                      
                            </div>
                
                            </a>
                
                    </div>
                 
                           
             
              </div>
                </div>
                {% endfor %}
                {% else %}
                
                        <div class="col-md-8 ml-auto mr-auto text-center">
                                <div class="card card-pricing card-plain">
                                        <div class="card-body " style="background-color: rgb(255, 255, 255)">
                          <h2 class="title">Bummer No products found in {{ category.name }} Category</h2>
                                         
                        </div>
                    </div>
                        </div>
                      </div>
                 
                      <div class="row">
                        <div class="col-md-8 col-lg-12 text-center">
                         
                                <h3><small>Kindly try by browsing other options</small></h3>
                            
                              
                          <!-- <div class=" justify-content-center">
                            <a href="" class="btn btn-outline-primary ">Browser courses? </a>                             
                        </div> -->
                            </div>
                 
                        
                                      
                    
                        
                
                  
                  {% endif %}
                <!-- <div class="col-12">
                    <nav aria-label="...">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div> -->
            </div>
        </div>

    </div>
</div>

       
          
           
      
                  
       <!--           {% if products%}
      {% else %}
        <h1><strong> BUMMER!! </strong>nothing found in selected category .</h1>
        <h3> <a href="{% url 'shop:contact' %}">Chat</a>  with us so that we find you your prefered Item</h3>
        <h4>We are dedicated to bring you the best curated <strong>curio merchandise around Africa</strong></h4>
        <h5><a href="{% url 'shop:product_list' %}">continue shopping</a></h5>
        <br>
        <img src="../../static/images/logincurio.png" alt="" style="width:150px; height:40px ">
      {% endif %}
            -->
                <!-- <div class="col-12">
                    <nav aria-label="...">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
    -->


                        {% endblock %}