cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views
from django.urls import path, re_path






urlpatterns = [
   

      # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')),
    re_path(r'', include('account.urls')),
    re_path(r'cart', include('cart.urls')),
    re_path(r'orders/', include('orders.urls')),
    re_path(r'', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from . import views

app_name = 'shop'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^vendorrequest/', views.vendorrequest, name='vendorrequest'),
    url(r'^Vendorfaqs/', views.Vendorfaqs, name='Vendorfaqs'),
    url(r'^log/', views.log, name='log'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^mens/', views.mens, name='mens'),
    url(r'^womens/', views.womens, name='womens'),
    url(r'^decorbeauty/', views.decorbeauty, name='decorbeauty'),
    url(r'^homeaccesories/', views.homeaccesories, name='homeaccesories'),
    url(r'^negotiate/price/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.client_price, name='client_price'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^negotiate/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.negotiate, name='negotiate'),

   
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),

    url(r'^(?P<subcategory_slug>[-\w]+)/$',
        views.subcategory_list, name='product_list_by_subcategory'),
    url(r'^(?P<minicategory_slug>[-\w]+)/$',
        views.minicategory_list, name='product_list_by_minicategory')




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.core.validators import MinValueValidator, \
    MaxValueValidator
from shop.models import Product
from account.models import Client


class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        
        return sum(item.get_cost() for item in self.items.all()) 

    def get_discount(self, client):
        total = float(self.get_total_cost())
        if client.has_discount:
            if client.no_of_orders == 1:
                self.discount = total * 0.1
                print(self.discount)
                return self.discount
            elif client.no_of_orders > 3 and client.no_of_orders < 5:
                self.discount = total * 0.25
                print(self.discount)
                return self.discount
            else:
                self.discount = total * 0.40
                return self.discount
        else:
            return self.discount == 0

class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse
from pyuploadcare.dj.models import ImageField
from taggit.managers import TaggableManager




class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True, manual_crop="4:4",)
    title = models.CharField(max_length=150, db_index=True)
    

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])



class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)


    class Meta:
        ordering = ('name', )
        verbose_name = 'subcategory'
        verbose_name_plural = 'subcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_subcategory', args=[self.slug])


class MiniCategory(models.Model):
    category = models.ForeignKey(Category, related_name='categories', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, related_name='subcategories', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'minicategory'
        verbose_name_plural = 'minicategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, related_name='products', on_delete=models.CASCADE)
    minicategory = models.ForeignKey(MiniCategory, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    reject_price = models.DecimalField(max_digits=10, decimal_places=2)
    lowest_price_offer = models.DecimalField(max_digits=10, decimal_places=2)
    maximum_price_offer = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ImageField(blank=True, null=True, manual_crop="4:4",)
    tags = TaggableManager()
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    @property
    def original_price(self,request):
    	
    	return self.price 
    	

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    

shop/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, NumberInput, EmailInput
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



class NegotiateForm(forms.Form):
    client_price = forms.CharField(
        label='Your price',
        max_length=100,
        widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Your price'}),
        required=True,
    )

shop/views/forgot_password.py
import json
import random, string
from django.shortcuts import render
from django.core import serializers
from landpage.form import ForgotPasswordForm
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail

def forgot_password_page(request):
    form = ForgotPasswordForm()
    return render(request, 'offlandpage/page/forgot_password.html',{
        'form': form,
        'tab': 'forget_password',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })


def reset_password(request):
    response_data = {'status' : 'failure', 'message' : 'unknown error occured' }
    if request.is_ajax():
        if request.method == 'POST':
            form = ForgotPasswordForm(request.POST)
            # Validate the form: the captcha field will automatically
            # check the input
            if form.is_valid():
                # Get the email and then create a random password for the client
                # and send the client the new password to their email address.
                email = request.POST['email']
                new_password = create_random_password(email)
                response_data = send_email(email, new_password)
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


def random_word(length):
    return ''.join(random.choice("abcdefghijklmnopqrstuvwxyz123467890") for i in range(length))


def create_random_password(email):
    # Create new password
    new_password = random_word(8)
    
    # Update the user account
    user = User.objects.get(email=email)
    user.set_password(new_password)
    user.save()
    
    # Return the new password
    return new_password


def send_email(email, new_password):
    if settings.EMAIL_HOST_USER is '' or settings.EMAIL_HOST_PASSWORD is '':
        return {'status' : 'failed', 'message' : 'cannot change password, emailer is offline, please check back later' }
    
    text = "Your new password is: " + new_password
            
    send_mail(
        "New Password",
        text,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False
    )
    return {'status' : 'success', 'message' : 'successfully registered' }

shop/views/google.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.conf import settings


def google_verify_page(request):
    return render(request, 'misc/google.html',{})

shop/views/landpageprod.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings

shop/views/privacy.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def privacy_page(request):
    return render(request, 'offlandpage/page/privacy.html',{
        'tab': 'privacy',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/terms.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def terms_page(request):
    return render(request, 'offlandpage/page/terms.html',{
        'tab': 'terms',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/txt.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def robots_txt_page(request):
    return render(request, 'misc/robots.txt', {}, content_type="text/plain")


def humans_txt_page(request):
    return render(request, 'misc/humans.txt', {}, content_type="text/plain")


def terms_txt_page(request):
    return render(request, 'misc/terms.txt', {}, content_type="text/plain")


def privacy_txt_page(request):
    return render(request, 'misc/privacy.txt', {}, content_type="text/plain")

shop/templates/shop/homepage/page/home2.html
{% load static %}


{% block content %}

<div>
        {% for c in categories %}
   <a href="{{ c.get_absolute_url }}">{{ c.name}}</a> 
        {% endfor %}
</div><br>
<div>    

        {% for sub in subcategories %}
        <a href="{{ sub.get_absolute_url }}">{{ sub.name}}</a> 
        {% endfor %}
</div>
<br>
<div>    

{% for mini in minicategories %}
<a href="{{ mini.get_absolute_url }}">{{ mini.name}}</a> 
{% endfor %}
</div>


    


{%  endblock  %}

shop/templates/shop/homepage/page/jsmodal.html
{% load staticfiles %}
<script>
/**
 *  Function will call AJAX function to load the particular course preview.
 */
function ajax_popup_course_preview(course_id)
{
    var url = 'course_preview_modal';
    $.ajax( url, {
        data: {
           'course_id': course_id,
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_course_preview').html(result); // Update UI.
            $('#course_preview_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
       }
    });
}
        
/**
 *  Function will call AJAX function to load the login modal.
 */
function ajax_logout()
{
    var url = '/logout';
            
    $.ajax( url, {
        data: {
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            window.location = '/shop';
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
        }
    });
}

function ajax_popup_login()
{
    var url = 'login_modal';
            
    $.ajax( url, {
        data: {
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_login').html(result); // Update UI.
            $('#login_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
        }
    });
}
        
/**
 *  Function will call AJAX function to load the register.
 */
function ajax_popup_register()
{
    var url = 'register_modal';
            
    $.ajax( url, {
        data: {
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_register').html(result); // Update UI.
            $('#register_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
        }
    });
}

/**
 *  Sends a message.
 */
/**
 *  Function will call AJAX function to load the register.
 */
function ajax_send_message()
{
    $('#id_send_msg_btn').prop("disabled", true);
    $.ajax( 'save_contact_us_message', {
           data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'name': $("#id_name").val(),
                'email': $("#id_email").val(),
                'phone': $("#id_phone").val(),
                'message': $("#id_message").val(),
                'captcha_0': $("#id_captcha_0").val(),
                'captcha_1': $("#id_captcha_1").val(),
           },
           type: 'post',
           success: function(result) {
                // success code execution here
                if (result.status == 'success')
                {
                    $('#id_contact_name_danger').html('');
                    $('#id_contact_email_danger').html('');
                    $('#id_contact_phone_danger').html('');
                    $('#id_contact_message_danger').html('');
                    $('#id_contact_captcha_danger').html('');
                    alert("Message sent!");
                    window.location = ''
                }
                else
                {
                    refresh_captcha();
                    var data = $.parseJSON(result.message)
                    var name_msg = '';
                    var email_msg = '';
                    var phone_msg = '';
                    var message_msg = '';
                    var captcha_msg = '';
                    for (var key in data) {
                        if (data.hasOwnProperty(key)) {
                            if (key == 'name')
                            {
                                name_msg = data[key];
                            }
                            if (key == 'email')
                            {
                                email_msg = data[key];
                            }
                            if (key == 'phone')
                            {
                                phone_msg = data[key];
                            }
                            if (key == 'message')
                            {
                                message_msg = data[key];
                            }
                            if (key == 'captcha')
                            {
                                captcha_msg = data[key];
                            }
                        }
                    }
           
                    $('#id_contact_name_danger').html(name_msg);
                    $('#id_contact_email_danger').html(email_msg);
                    $('#id_contact_phone_danger').html(phone_msg);
                    $('#id_contact_message_danger').html(message_msg);
                    $('#id_contact_captcha_danger').html(captcha_msg);
                }
           },
           error: function(xhr,status,error) {
                // error code here
           },
           complete: function(xhr,status) {
                // completion code here
                $('#id_send_msg_btn').prop("disabled", false);
           }
    });
}


/**
 * The following function will cause the captcha to refresh.
 */
function refresh_captcha()
{
    var url = location.protocol + "//" + window.location.hostname + ":" + location.port + "/captcha/refresh/";
    
    // Make the AJAX-call
    $.getJSON(url, {}, function(json) {
              //var $form = $('modal-body').parents('register_form');
              var $form = $('#contactForm');
              $form.find('input[name="captcha_0"]').val(json.key);
              $form.find('img.captcha').attr('src', json.image_url);
              });
              return false;
}

// Add refresh button after field (this can be done in the template as well)
$('img.captcha').after(
    $('<a href="#void" class="captcha-refresh">Refresh</a>')
);

// Click-handler for the refresh-link
$('.captcha-refresh').click(function(){
    refresh_captcha();
});
</script>

shop/templates/shop/homepage/page/vendorfaqs.html
{% extends 'shop/homepage/base2.html' %}

{% load static %}



{% block content %}









<nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg " color-on-scroll="100" id="sectionsNav">
        <div class="container">
          <div class="navbar-translate">
            <a><img src="../../static/img/jadili.png" alt="" style="width:180px; height:100px "></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon"></span>
              <span class="navbar-toggler-icon"></span>
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <!-- <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <i class="material-icons">apps</i> Components
                </a>
                <div class="dropdown-menu dropdown-with-icons">
                  <a href="../presentation.html" class="dropdown-item">
                    <i class="material-icons">layers</i> Presentation
                  </a>
                  <a href="../index.html" class="dropdown-item">
                    <i class="material-icons">line_style</i> All Components
                  </a>
                  <a href="../docs/2.1/getting-started/introduction.html" class="dropdown-item">
                    <i class="material-icons">content_paste</i> Documentation
                  </a>
                </div>
              </li> -->
             
              <li class="button-container nav-item iframe-extern">
                <a href="{% url 'shop:product_list' %}"  class="btn  btn-primary   btn-round btn-block">
                   Shop
                </a>
              </li>
              <li class="button-container nav-item iframe-extern">
                    <a href="{% url 'shop:home' %}"  class="btn  btn-primary   btn-round btn-block">
                       Shoppers FAQs
                    </a>
                  </li>
          
              <li class="button-container nav-item iframe-extern">
                <a href="{% url 'shop:home' %}"  class="btn  btn-primary   btn-round btn-block">
                  Back to home
                </a>
              </li>
    
           
            </ul>
          </div>
        </div>
      </nav>



      <div class="page-header header-filter" data-parallax="true" style="background-image: url('../assets/img/bg8.jpg')">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h2 class="title">Frequently asked questions by other Vendors</h2>
              <h4>If you can't find an answer to your question. Kindly don't hesitate to contact us here  <a href="{% url 'shop:Vendorfaqs' %}" >Contact us </h4>
              <br>
           
            </div>
          </div>
        </div>
      </div>
      <div class="main main-raised">
        <div class="container">
          <div class="section text-center">
           
             <!--                 collapse -->
        <div id="collapse">
                <div class="mtitle">
                  <h3>Questions</h3>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div id="accordion" role="tablist">
                      <div class="card card-collapse">
                        <div class="card-header" role="tab" id="headingOne">
                          <h5 class="mb-0">
                            <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Question #1
                              <i class="material-icons">keyboard_arrow_down</i>
                            </a>
                          </h5>
                        </div>
                        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                          <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                          </div>
                        </div>
                      </div>
                      <div class="card card-collapse">
                        <div class="card-header" role="tab" id="headingTwo">
                          <h5 class="mb-0">
                            <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Question #2
                              <i class="material-icons">keyboard_arrow_down</i>
                            </a>
                          </h5>
                        </div>
                        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                          <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                          </div>
                        </div>
                      </div>
                      <div class="card card-collapse">
                        <div class="card-header" role="tab" id="headingThree">
                          <h5 class="mb-0">
                            <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Question #3
                              <i class="material-icons">keyboard_arrow_down</i>
                            </a>
                          </h5>
                        </div>
                        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
                          <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!--                 end collapse -->
          </div>
       
          
        </div>
      </div>
    



              <footer class="footer footer-default">
                    <div class="container">
                      <nav class="float-left">
                        <ul>
                          <li>
                            <a href="#">
                             Facebook
                            </a>
                          </li>
                          <li>
                            <a href="#">
                             Twitter
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              IG
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              FAQs
                            </a>
                          </li>
                        </ul>
                      </nav>
                      <div class="copyright float-right">
                        &copy;
                        <script>
                          document.write(new Date().getFullYear())
                        </script> Jadili Mall 
                        
                      </div>
                    </div>
                  </footer>             
              {% endblock %}